baseURL = "https://shamilnabiyev.github.io/"
languageCode = "en-us"
title = "Shamil's Blog"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.
ignoreErrors = ["error-missing-instagram-accesstoken"]

[taxonomies]
  tag = "tags"

[author]
    name = "kimcc"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
    math = true
    # Blog description at the top of the homepage. Supports markdown.
    description = "Hey, my name is Shamil Nabiyev. Welcome to my blog."

    showReadMore = true

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

    # Add links to your accounts. Remove the ones you don't want to include.
    # Main
    email = "shamil.nabiyev@stud.h-da.de"
    linkedin = "https://de.linkedin.com/in/shamil-nabiyev"

    # Writing
    # medium = "#"

    # Programming
    github = "https://github.com/shamilnabiyev"
    # stackoverflow = "#"
    # gitlab = "#"
    # codepen = "#"

    # Academic
    googlescholar = "https://scholar.google.com/citations?user=ZZP59ioAAAAJ"
    researchgate = "https://www.researchgate.net/profile/Shamil_Nabiyev"

# Menu links along the sidebar navigation.
[[menu.main]]
    identifier = "homepage"
    name = "Homepage"
    url = "/"
    weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[[menu.main]]
    name = "Archives"
    identifier = "archives"
    url = "/archives/"
    weight = 4

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = true
